- hosts: vagrant-production
  become: yes
  tasks:
    - name: Remove all current assets
      become_user: guestbook
      file:
        path: /home/guestbook/www
        state: absent
    
    - name: Upload and extract new version
      become_user: guestbook
      unarchive:
        src: '{{ tar_path }}'
        dest: /home/guestbook/
        
    - name: Set up backend url for frontend app
      become_user: guestbook
      copy:
        content: "window.__backendUrl = 'http://192.168.33.10:8080/'"
        dest: /home/guestbook/www/backendUrl.js
      
      
    
