- hosts: vagrant-production
  become: yes
  tasks:
    - name: Remove all current assets
      become_user: guestbook
      file:
        path: /home/guestbook/www
        state: absent
    
    - name: Upload and extract new version
      become_user: guestbook
      unarchive:
        src: '{{ tar_path }}'
        dest: /home/guestbook/
      
      
    
