- hosts: vagrant-production
  become: yes
  tasks:
    - name: Upload .jar
      become_user: guestbook
      copy:
        src: '{{ jar_path }}'
        dest: /home/guestbook/app.jar
    
    - name: Restart backend service
      service:
        name: guestbook
        state: restarted
      
      
    
