- hosts: vagrant-jenkins
  become: yes
  tasks:
  
    - name: Install MySQL and MySQL Python integration for Ansible
      apt:
        name: '{{ item }}'
        state: present
      with_items:
        - mysql-server
        - python-mysqldb
        
    - name: Drop guestbook test database
      mysql_db:
        name: guestbook
        state: absent
        
    - name: Add guestbook-test mysql user
      mysql_user:
        name: guestbook
        password: '{{ db_password }}'
        priv: '*.*:ALL'
        state: present
        
    - name: Recreate guestbook test database
      mysql_db:
        name: guestbook-integrationtest
        state: present
        
        
    
