- name: Install Java 8 JRE, MySQL and MySQL Python integration for Ansible
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - openjdk-8-jre
    - mysql-server
    - python-mysqldb
    
- name: Add guestbook mysql user
  mysql_user:
    name: guestbook
    password: guestbook
    priv: '*.*:ALL'
    state: present
    
- name: Add guestbook production database
  mysql_db:
    name: guestbook-prod
    state: present
    
- name: Copy systemd service definition file
  template:
    src: guestbook.service
    dest: /etc/systemd/system/
    
- name: Reload systemd configuration
  command: systemctl daemon-reload

- name: Enable backend service
  service:
    name: guestbook
    enabled: true
