- name: Install Apache
  apt:
    name: apache2
    state: present
    
- name: Copy site Apache config
  template:
    src: guestbook.conf
    dest: /etc/apache2/sites-available/guestbook.conf

- name: Disable default Apache config
  command: a2dissite 000-default.conf
  
- name: Enable site Apache config
  command: a2ensite guestbook.conf
    
- name: Create folder for frontend assets
  file:
    path: /home/guestbook/www
    state: directory
    
- name: Restart apache
  service:
    name: apache2
    state: restarted